// <auto-generated />
using System;
using Infinity.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infinity.WebApi.Migrations
{
    [DbContext(typeof(LocationsDbContext))]
    partial class LocationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infinity.WebApi.Models.Attraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("AvgRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("avg_rating");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrls")
                        .HasColumnType("jsonb")
                        .HasColumnName("image_urls");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("lat");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("lng");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("ParkId")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("park_id");

                    b.Property<int>("ReviewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("review_count");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.HasKey("Id");

                    b.HasIndex("ParkId")
                        .HasDatabaseName("idx_attractions_park_id");

                    b.ToTable("attractions", (string)null);
                });

            modelBuilder.Entity("Infinity.WebApi.Models.AttractionCategory", b =>
                {
                    b.Property<Guid>("AttractionId")
                        .HasColumnType("uuid")
                        .HasColumnName("attraction_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("AttractionId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("attraction_categories", (string)null);
                });

            modelBuilder.Entity("Infinity.WebApi.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Infinity.WebApi.Models.Park", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("lat");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("lng");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Resort")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("resort");

                    b.HasKey("Id");

                    b.ToTable("parks", (string)null);
                });

            modelBuilder.Entity("Infinity.WebApi.Models.Attraction", b =>
                {
                    b.HasOne("Infinity.WebApi.Models.Park", "Park")
                        .WithMany("Attractions")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Park");
                });

            modelBuilder.Entity("Infinity.WebApi.Models.AttractionCategory", b =>
                {
                    b.HasOne("Infinity.WebApi.Models.Attraction", "Attraction")
                        .WithMany("AttractionCategories")
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infinity.WebApi.Models.Category", "Category")
                        .WithMany("AttractionCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attraction");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Infinity.WebApi.Models.Attraction", b =>
                {
                    b.Navigation("AttractionCategories");
                });

            modelBuilder.Entity("Infinity.WebApi.Models.Category", b =>
                {
                    b.Navigation("AttractionCategories");
                });

            modelBuilder.Entity("Infinity.WebApi.Models.Park", b =>
                {
                    b.Navigation("Attractions");
                });
#pragma warning restore 612, 618
        }
    }
}
